### ISSUE TITLE
tflite model

### ISSUE THREAD

**Issue by nliaudat** [JarmouniA/Kaggle_HandwrittenDigits_Inference_ESP32#1]
Hi, 
Many thanks for your project. 
Can you post your tf lite model ?
I'll make some test to enhance https://github.com/jomjol/AI-on-the-edge-device
Regards

**Comment by JarmouniA** [comment]
Hello,
TF Lite & Micro models can be found in /TF_models
Regards

**Comment by nliaudat** [comment]
Many thanks
